### ISSUE TITLE
Error 500 when order is placed

### ISSUE THREAD

**Issue by jvmonjo** [shyim/shopware-image#2]
With the bare minimum store and the demo data there are some pages that cause 500 error (caprover logs don't help much, just show a 500 error).

You can try it out by placing an order with the demo data.

**Comment by shyim** [comment]
Can't reproduce it. 
Maybe smtp server credentials wrong. Start with APP_ENV=dev

**Comment by jvmonjo** [comment]
That was it. Sorry to have opened an issue. I had a blank space at the end of the smtp address. I couldn't find the answer elsewhere. You saved me! Thank you for your work on the one click caprover app.
