### ISSUE TITLE
use of ACTIVE_PLUGINS env variable

### ISSUE THREAD

**Issue by agebeyaw** [shyim/shopware-image#3]
I would like to specify list of default plugins and I see that there is this `ACTIVE_PLUGINS` env variable. Where is it used? Thank you!

**Comment by shyim** [comment]
You can specificy an list of plugins which are already present to be installed and activated

https://github.com/shyim/shopware-image/blob/master/rootfs/etc/shopware/scripts/on-startup/plugin.sh#L3
